### ISSUE TITLE
I uploaded the theme in a SearXNG Fork - theme not working :(

### ISSUE THREAD

**Issue by TBNRDev** [reeseovine/searx-material#3]
not working :(  ?
![image](https://user-images.githubusercontent.com/108610517/209458472-b3cc75a1-e407-4733-ae25-b8e9356fb106.png)

**Comment by reeseovine** [comment]
Sorry, I haven't worked on this in a long time. The SearxNG port is unfinished and shouldn't be expected to work. You might want to see the `main` branch which I just made the default again.
